Repository SIS-Team-8/2024-SIS-Team-8, pull requests merged in 2024-10, with the labels that each got.

#15 Alexandar/moodlogging sceen fix
  client/src/pages/MoodSelection.css
  client/src/pages/MoodSelection.js
Labels: enhancement

#16 Marcus/login api
  README.md
  server/controllers/AuthController.js
  server/controllers/CalendarController.js
  server/controllers/EmoteController.js
  server/controllers/HistoryController.js
  server/controllers/ProfileController.js
  server/middlewares/AuthMiddleware.js
  server/middlewares/authMiddlewares.js
  server/models/UserModel.js
  server/package-lock.json
  server/routes/ApiRoute.js
  server/routes/AuthRoute.js
  server/routes/OLD_MongoRoute.js
  server/server.js
Labels: feature, backend

#17 Ishaan/fixes
  client/src/components/BarChart.js
  client/src/pages/Calendar.css
  client/src/pages/Calendar.js
  client/src/pages/DailyView.css
  client/src/pages/DailyView.js
  client/src/pages/History.css
  client/src/pages/History.js
Labels: enhancement

#18 Alexandar nikolic/onboarding pages
  client/src/App.js
  client/src/assets/calendar.png
  client/src/assets/daily-view.png
  client/src/assets/history.png
  client/src/assets/log-daily-emotion.png
  client/src/assets/menu.png
  client/src/assets/mood-logging.png
  client/src/pages/Help.css
  client/src/pages/Help.js
  client/src/pages/Onboarding.css
  client/src/pages/Onboarding.js
  client/src/pages/OnboardingOverview.js
Labels: feature

#19 Pulkit/settings screen fixes
  client/src/App.css
  client/src/App.js
  client/src/components/BarChart.css
  client/src/components/BarChart.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/pages/Calendar.css
  client/src/pages/Calendar.js
  client/src/pages/DailyView.css
  client/src/pages/DailyView.js
  client/src/pages/Help.css
  client/src/pages/Help.js
  client/src/pages/History.css
  client/src/pages/History.js
  client/src/pages/Login.css
  client/src/pages/Login.js
  client/src/pages/MoodSelection.css
  client/src/pages/MoodSelection.js
  client/src/pages/OnboardingOverview.js
  client/src/pages/Profile.css
  client/src/pages/Profile.js
  client/src/pages/Settings.css
  client/src/pages/Settings.js
  client/src/pages/SignUp.css
  client/src/pages/SignUp.js
  client/src/pages/SplashScreen.js
Labels: enhancement

#20 Alexandar nikolic/sign up linking
  client/src/App.js
  client/src/pages/SignUp.js
Labels: feature

#21 Andreas/login linking
  client/src/App.js
  client/src/pages/Login.js
  client/src/pages/SignUp.js
Labels: feature

#22 Backend Bugfixes and additional APIs
  README.md
  server/controllers/ProfileController.js
  server/models/UserModel.js
  server/routes/ApiRoute.js
Labels: bug, feature, backend

#23 Alexandar nikolic/profile full stack
  client/src/App.js
  client/src/assets/profile-placeholder.jpg
  client/src/pages/Login.js
  client/src/pages/Onboarding.js
  client/src/pages/Profile.css
  client/src/pages/Profile.js
  client/src/pages/ResetPassword.css
  client/src/pages/ResetPassword.js
  client/src/pages/SignUp.js
  server/controllers/ProfileController.js
  server/routes/ApiRoute.js
  server/server.js
Labels: enhancement, feature

#24 Marcus/backend
  README.md
  server/controllers/EmoteController.js
  server/routes/ApiRoute.js
Labels: feature, backend

#25 Alexandar nikolic/moodlogging and calendar linking
  client/src/App.js
  client/src/pages/Calendar.js
  client/src/pages/DailyView.css
  client/src/pages/DailyView.js
  client/src/pages/MoodSelection.css
  client/src/pages/MoodSelection.js
  client/src/pages/Profile.js
  client/src/pages/SignUp.js
  server/controllers/EmoteController.js
Labels: feature

#26 Andreas/history full stack
  client/src/components/BarChart.js
  client/src/pages/History.js
  server/controllers/HistoryController.js
Labels: feature
